const mongoose = require('mongoose');
const Schema = mongoose.Schema;

let businessSchema = new Schema({
	Name	:{type: String},
	Company	:{type: String},
	Address	:{type: String},
	Address2 :{type: String},	
	City	:{type: String},
	State	:{type: String},
	Zip		:{type: String},
	Zip4	:{type: String},
	Zip9	:{type: String},
	Latitude :{type: String},	
	Longitude :{type: String},	
	County	:{type: String},
	Area_Code	:{type: String},
	Telephone_Number	:{type: String},
	Toll_Free_Number:{type: String},	
	Fax_Number	:{type: String},
	Contact_Gender	:{type: String},
	Title_Code_1	:{type: String},
	Title_Code_2	:{type: String},
	Title_Code_3	:{type: String},
	Title_Code_4	:{type: String},
	Ethnic_Code	:{type: String},
	Ethnic_Group	:{type: String},
	Language_Code	:{type: String},
	Religion_Code	:{type: String},
	Web_Address	:{type: String},
	Total_Employees_Corp_Wide :{type: String},	
	Total_Revenue_Corp_Wide	:{type: String},
	NAICS_1	:{type: String},
	NAICS_2	:{type: String},
	NAICS_3	:{type: String},
	NAICS_4	:{type: String},
	MinorityOwned	:{type: String},
	SmallBusiness	:{type: String},
	LargeBusiness	:{type: String},
	HomeBusiness	:{type: String},
	ImportExport	:{type: String},
	PublicCompany	:{type: String},
	Headquarters_Branch	:{type: String},
	StockExchange	:{type: String},
	FranchiseFlag	:{type: String},
	IndividualFirm_Code	:{type: String},
	SIC8_1	:{type: String},
	SIC8_1_2 :{type: String},	
	SIC8_1_4 :{type: String},	
	SIC8_1_6 :{type: String},	
	StockTicker	:{type: String},
	FortuneRank	:{type: String},
	ProfessionalAmount	:{type: String},
	ProfessionalFlag	:{type: String},
	Ad_Size	:{type: String},
	FemaleOwnedorOperated	:{type: String},
	CityPopulation	:{type: String},
	ParentForeignEntity	:{type: String},
	WhiteCollarCode	:{type: String},
	GovernmentType	:{type: String},
	Residential_Business_Code	:{type: String},
	Email	:{type: String},
	Title_Full	:{type: String},
	Phone_Contact	:{type: String},
	Other_Company_Name	:{type: String},
	Credit_Score	:{type: String},
	Title_Code_1_Desc	:{type: String},
	Title_Code_2_Desc:{type: String},
	createdAt: {
        type: Date,
        default: Date.now
    },
    updatedAt: {
        type: Date,
        default: Date.now
    }
});

module.exports = mongoose.model('Business', businessSchema);