const mongoose = require('mongoose');
const Schema = mongoose.Schema;

let consumerSchema = new Schema({
	personfirstname	:{type: String},
	personmiddleinitial	:{type: String},
	personlastname	:{type: String},
	persontitleofrespect	:{type: String},
	streetname	:{type: String},
	streetsuffix:{type: String},	
	primaryaddress	:{type: String},
	secondaryaddress:{type: String},	
	citynameabbr:{type: String},	
	cityname	:{type: String},
	state	:{type: String},
	ZipCode	:{type: String},
	Zip_4	:{type: String},
	msa		:{type: String},
	countycode	:{type: String},
	countyname	:{type: String},
	carrier_route :{type: String},	
	latitude	:{type: String},
	longitude	:{type: String},
	timezone	:{type: String},
	dwellingtype :{type: String},	
	livingunitid :{type: String},	
	AreaCode	:{type: String},
	Phone	:{type: String},
	FullPhoneNumber	:{type: String},
	MobilePhoneNumber	:{type: String},
	estimatedincomecode	:{type: String},
	homeownerprobabilitymodel:{type: String},	
	numberofpersonsinlivingunit	:{type: String},
	presenceofchildren	:{type: String},
	persongender	:{type: String},
	persondateofbirthyear	:{type: String},
	persondateofbirthmonth	:{type: String},
	persondateofbirthday :{type: String},	
	personexactage	:{type: String},
	personmaritalstatus	:{type: String},
	occupationgroup	:{type: String},
	personoccupation	:{type: String},
	ethniccode	:{type: String},
	languagecode	:{type: String},
	ethnicgroup	:{type: String},
	religioncode :{type: String},	
	hispaniccountrycode	:{type: String},
	personeducation	:{type: String},
	businessowner	:{type: String},
	NumberOfAdults	:{type: String},
	PresenceOfCreditCard :{type: String},	
	PresenceOfBankCard	:{type: String},
	GasDeptRetailCardHolder	:{type: String},
	CreditRating	:{type: String},
	investment	:{type: String},
	investmentstocksecurities	:{type: String},
	Networth	:{type: String},
	NumberOfLinesOfCredit	:{type: String},
	Credit_RangeOfNewCredit	:{type: String},
	Investing_Active :{type: String},
	InvestmentsPersonal	:{type: String},
	InvestmentsRealEstate	:{type: String},
	InvestingFinanceGrouping	:{type: String},
	InvestmentsForeign	:{type: String},
	InvestmentEstimatedResidentialPropertiesOwned	:{type: String},
	AssimilationCodes	:{type: String},
	traveler	:{type: String},
	pets	:{type: String},
	cats	:{type: String},
	dogs	:{type: String},
	mailresponder	:{type: String},
	sweepstakes	:{type: String},
	religiouscontributor	:{type: String},
	politicalcontributor	:{type: String},
	health_institutioncontributor	:{type: String},
	charitable	:{type: String},
	generalcontributor	:{type: String},
	donatestoenvironmentalcauses	:{type: String},
	donatesbymail	:{type: String},
	veteraninhousehold	:{type: String},
	HeavyBusinessTravelers	:{type: String},
	hightechleader	:{type: String},
	Smoker	:{type: String},
	MailOrderBuyer	:{type: String},
	OnlinePurchasingIndicator	:{type: String},
	EnvironmentalIssuesCharitableDonation	:{type: String},
	InternationalAidCharitableDonation	:{type: String},
	PoliticalCharitableDonation	:{type: String},
	PoliticalConservativeCharitableDonation	:{type: String},
	PoliticalLiberalCharitableDonation	:{type: String},
	VeteransCharitableDonation	:{type: String},
	CharitableDonations_Other	:{type: String},
	homeswimmingpoolindicator	:{type: String},
	airconditioning	:{type: String},
	homeheatindicator	:{type: String},
	DONOTCALL	:{type: String},
	DONOTCALLUpdate	:{type: String},
	Name	:{type: String},
	UPDATE_SOURCE	:{type: String},
	Email:{type: String},
	createdAt: {
        type: Date,
        default: Date.now
    },
    updatedAt: {
        type: Date,
        default: Date.now
    }
});


// Export the model
module.exports = mongoose.model('Consumer', consumerSchema);